### ISSUE TITLE
Publish Delta Lake quickstart Docker image to Dockerhub

### ISSUE THREAD

**Issue by P7h** [delta-io/delta-docs#48]
@dennyglee any thoughts here?
I think it would be wonderful and will help many developers if we publish the Delta Lake quickstart Docker image to Dockerhub.
That way developers can directly jump into experimenting with Delta Lake by running it.
Right now the first step is to build the image, which takes a bit of time as we have a few depndencies.

**Comment by dennyglee** [comment]
Hi @P7h - just uploaded a version at https://go.delta.io/dockerhub - could you validate that this works as expected?

**Comment by dennyglee** [comment]
Including #50 to update the readme.md to include Docker instructions

**Comment by P7h** [comment]
Thanks @dennyglee for working on this and publishing the Docker image to the DockerHub.
I ran through all the steps of the README on MacBook Pro M2 [2022] and the [arm64] image i.e. `deltaio/delta-docker:0.8.1_2.3.0_arm64` works all fine.

2 minor things though:
1. https://go.delta.io/dockerhub is prompting me to login. When I unfurled the go link, it seems to be going to https://hub.docker.com/repository/docker/deltaio/delta-docker/ which requires the user to login. 
- Please could you change the target for the above go link to point to: https://hub.docker.com/r/deltaio/delta-docker
- Also this needs to be fixed in the README [this specific line: Note, you can also download the image from [https://go.delta.io/dockerhub](https://go.delta.io/dockerhub)] as well as on the DockerHub instructions page [this specific line: See the [Delta Lake DockerHub](https://hub.docker.com/repository/docker/deltaio/delta-docker/) to download the docker directly].
2. All the steps in the README of the [quickstart_docker](https://github.com/delta-io/delta-docs/tree/main/static/quickstart_docker) would need a bit of tweaking.
For example:
`docker run --name delta_quickstart --rm -it --entrypoint bash delta_quickstart`
Needs to be replaced with the following or the amd64 image depending on the OS flavour:
`docker run --name delta_quickstart --rm -it --entrypoint bash deltaio/delta-docker:0.8.1_2.3.0_arm64` 
However I can see the README instructions becoming unwieldy with the 2 OS flavours on top of the existing steps for the docker image built from the source. How do you think we should go about this? 
Would it help if we highlight in a subtle way right after the above DockerHub reference in the README that if you are using DockerHub image, replace the last occurrence of `delta_quickstart` with `deltaio/delta-docker:0.8.1_2.3.0_arm64` (or the amd64 image) in the rest of the instructions?

**Comment by P7h** [comment]
> Including #50 to update the readme.md to include Docker instructions

I dint encounter this issue though. Everything ran out of the box without executing this command.

**Comment by dennyglee** [comment]
@P7h the instructions we left were for the build version. Should we perhaps provide different instructions for build vs dockerhub?  

I think you're right but I'm also concerned on how to reduce the size of the readme as it's pretty huge as it is.  Let me noodle on this to see if we can shrink it down.

**Comment by dennyglee** [comment]
@P7h please take a look at the updated `readme.md` and see what you think?  thanks!

**Comment by P7h** [comment]
I see 2 Dockerfiles now, guess we are planning to support multiple `deltalake` versions. 
There are a few changes required in the current README. I am unable to clone your repo as I already have the repo with the same name.
ROAPI's command should be the following as we need 8080 port open for curl commands:
```shell
docker run --name delta_quickstart --rm -it -p 8080:8080 --entrypoint bash deltaio/delta-docker:0.8.1_2.3.0_arm64
```
Probably we can discuss offline.
I will make the changes offline and share the latest README with you, so you can commit directly, if that's ok with you.

**Comment by dennyglee** [comment]
Sure, though note in this example, you're running the commands in the docker itself using the same terminal (hence the nohup).

**Comment by P7h** [comment]
Thanks @dennyglee. 
I removed the redundant step 4 and sent a pull request #51.
